version: '3'

services:
  backend:
    env_file:
        "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "tap2trade/backend"
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "tap2trade/frontend"
    stdin_open: true
    ports:
      - "3030:80"
    links:
      - "backend:be"